### ISSUE TITLE
Packaging and Deployment section needs work

### ISSUE THREAD

**Issue by bossidy** [RackHD/docs#181]
o	Install Supplementary Files (Ubuntu)
o	Retrieve the Installer/Distribution Media (Ubuntu)
o	Add Ansible Playbook for Post-OS Install: (Ubuntu)

**Comment by bossidy** [comment]
The instructions for installing the RackHD packages (http://rackhd.readthedocs.org/en/latest/packaging_and_deployment.html) does not mention the following repos:

onserve
on-core
RackHD
on-imagebuilder
on-tools
on-statsd

Should I add them?

**Comment by heckj** [comment]
Nope - onserve won’t be staying, and the others are ancilliary or installed with installing the other packages, part of development, not an installation

-joe

**Comment by bossidy** [comment]
Thanks
