### ISSUE TITLE
Fix wording on opening slide.

### ISSUE THREAD

**Issue by sscaringella** [RackHD/docs#197]
Please replace the following content on the opening page and any other places it might be referenced.

Developers can use the RackHD API to create a user interface that serves as a single point of access for managing hardware services regardless of the underlying hardware in place. 

With this new content:
Developers can use the RackHD APIs as a component in a larger orchestration system or to create a user interface for managing hardware services regardless of the underlying hardware in place.

**Comment by bossidy** [comment]
OK, thanks for the revision.
