### ISSUE TITLE
Update Quick Setup Section

### ISSUE THREAD

**Issue by bossidy** [RackHD/docs#200]
There are differences between what we now have and https://github.com/RackHD/RackHD/blob/master/example/README.md.

Should I update the doc with what's in the readme?

**Comment by heckj** [comment]
That would be awesome, thank you. Have been meaning to do that for past two days, but got caught with other work first

-joe

On Dec 2, 2015, at 8:28 AM, bossidy <notifications@github.com<mailto:notifications@github.com>> wrote:


There are differences between what we now have and https://github.com/RackHD/RackHD/blob/master/example/README.md.

Should I update the doc with what's in the readme?

**Comment by bossidy** [comment]
In the README.md, there is no step for powering on PXE clients (vboxmanage startvm pxe-1 --type gui). Was that purposely omitted?

**Comment by heckj** [comment]
just a miss on my part - I was focused on the content to get the CoreOS installation process working

**Comment by bossidy** [comment]
OK, I'll add it....

**Comment by bossidy** [comment]
Oooops

**Comment by bossidy** [comment]
Joe, because most of this is script-based, I'm fuzzy about where everything is running in this quick deployment. Aw, it'll be easier to send you a couple of diagrams in an email....

**Comment by bossidy** [comment]
I'm going to stay away from this section until the final solution is implemented.
