### ISSUE TITLE
Language related to Linux/WinPE/DOS bootstrapping claims is too colloquial?

### ISSUE THREAD

**Issue by benbp** [RackHD/docs#75]
I'm wondering if we want to change the language/voice in the sentence quoted below. It seems a little colloquial, like something spoken in a live pitch, rather than the language of documentation.

`"The default and most commonly used microkernel is based on Linux, although we have also built and run WinPE and even DOS microkernels."` (from the first paragraph in http://rackhd.readthedocs.org/en/latest/software_architecture.html)

Perhaps something like:

`"The default and most commonly used microkernel is based on Linux, although WinPE and DOS netbooting is also possible."` (We do have active support for WinPE and DOS booting, with a small amount of legwork, so this statement is accurate).

**Comment by benbp** [comment]
@bossidy @christineday @heckj

**Comment by bossidy** [comment]
Works for me.

**Comment by heckj** [comment]
heh, clearly I wrote it :-) Good update.

**Comment by benbp** [comment]
@heckj ha! yeah I can spot your language like a hawk.
