### ISSUE TITLE
monorail.list entry for apt sources points to Crystal Yacht Cruise website???

### ISSUE THREAD

**Issue by benbp** [RackHD/docs#80]
We have instructions to add a monorail.list file to /etc/apt/sources.list.d/ in order to install monorail debian packages, but the IP specified in the list entry goes a website for Crystal Yacht Cruises...

`deb [arch=amd64] http://54.191.244.96/ trusty non-free`

From http://rackhd.readthedocs.org/en/latest/packaging_and_deployment.html section 5.2.1

**Comment by benbp** [comment]
@heckj

**Comment by heckj** [comment]
lol - leftover from the AWS instance we had ages ago that hosted a debian repo - yep - need to update

**Comment by benbp** [comment]
Hilarious.

**Comment by vaibhavkhanduja** [comment]
@heckj can let us know which is the right one?

**Comment by heckj** [comment]
@vaibhavkhanduja we don't have a public repository with debians in it yet set up - we're doing some poking on that very thing right now leveraging bintray, but work in progress. There's a debian directory in each of the repositories that you can use to build your own .deb files for deployment on Debian, Ubuntu, etc - just don't have that exposed externally as yet.
