### ISSUE TITLE
Reference to Apache2 for HTTP

### ISSUE THREAD

**Issue by king-jam** [RackHD/docs#95]
http://rackhd.readthedocs.org/en/latest/development_guide.html#hardware-discovery

Section references restart apache2 API server but on-http is all node.

**Comment by bossidy** [comment]
Should I remove that section?

**Comment by king-jam** [comment]
Sorry my link was referencing too high in the doc. See: 

http://rackhd.readthedocs.org/en/latest/development_guide.html#monorail-api

The section is useful. Maybe adjust it to: 

sudo service on-http stop
sudo service on-http start

and for the generating docs. I think 'npm run apidoc' might be better since 'sh HWIMO-BUILD' is designed to generate the debian packages

**Comment by benbp** [comment]
@bossidy yep, James' suggestions are correct.

**Comment by bossidy** [comment]
Made the changes. Thanks

**Comment by king-jam** [comment]
Thanks! Confirmed.
